### ISSUE TITLE
Make modules Debian 8 compatible

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1242]
Part of https://github.com/cargomedia/roadmap/issues/95

- [x] apt
- [x] autoprefixer
- [x] bash
- [x] bipbip
- [x] browserify
- [x] ca_certificates
- [x] database
- [x] ffmpeg
- [x] janus
- [x] lame
- [x] mysqltuner
- [x] nodejs
- [x] systemd
- [x] helper
- [x] build
- [x] cgi_fcgi
- [x] cm (#1254)
- [x] cm_janus
- [x] composer
- [x] coturn (#1384)
- [x] cron
- [x] daemon
- [x] elasticsearch
- [x] environment
- [x] fluentd
- [x] foreman
- [x] gearman
- [x] git
- [x] github
- [x] iptables
- [x] irqbalance
- [x] janus
- [x] kernel
- [x] lame
- [x] logrotate
- [x] memcached
- [x] mjr_convert
- [x] mongodb (https://github.com/cargomedia/puppet-packages/pull/1371)
- [x] monit
- [x] mysql (#1243)
- [x] mysql_proxy
- [x] mysqltuner
- [x] network
- [x] nginx
- [x] ntp
- [x] percona_toolkit
- [x] phantomjs
- [x] php5
- [x] phpunit
- [x] postfix
- [x] puppet
- [x] raid
- [x] redis
- [x] rsync
- [x] rsyslog
- [x] ruby
- [x] socket_redis
- [x] ssh
- [x] sudo
- [x] sysctl
- [x] timezone
- [x] ufw
- [x] uglify
- [x] ulimit
- [x] vim

**Comment by ppp0** [comment]
depends on https://github.com/cargomedia/puppet-packages/issues/1243

**Comment by ppp0** [comment]
depends on https://github.com/cargomedia/puppet-packages/issues/1244

**Comment by njam** [comment]
I've added a list to the description with puppet modules that are currently installed in SK, but only available for Debian 7.

**Comment by kris-lab** [comment]
All modules seems to be compatible with Jessie.

(coping some notes from [Janus ticket](https://github.com/cargomedia/puppet-packages/issues/1346#issuecomment-238521428)
- [ ] disable mongodb logs #1430
- [ ]  disable logs for janus #1377
- [ ]  foreman-debian cargomedia/pulsar-conf-cargomedia#331

**Comment by kris-lab** [comment]
Closing in favor of https://github.com/cargomedia/puppet-cargomedia/issues/1359
