### ISSUE TITLE
To-do for cm_janus

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#998]
Follow-up from #969 

- [x] Non-root user for daemon (#1002)
- [ ] Bipbip-plugin (see https://github.com/cargomedia/rndmvr-studio_agent/issues/2)
- [x] Upgrade cm-janus version (#1002)

what not

**Comment by njam** [comment]
How about using `version => 'latest'` for `cm-janus`, so we don't need to upgrade?

**Comment by ppp0** [comment]
good idea! (if there is no reengineering of args or config file involved)

**Comment by njam** [comment]
I suggest to rather do a bipbip plugin for janus (and not cm-janus)?
Closing in favor of https://github.com/cargomedia/puppet-packages/issues/1073
